RD /S /Q "Be.Windows.Forms.HexBox\obj"
DEL /Q /F /S "Be.Windows.Forms.HexBox\bin\Release\*.pdb"
RD /S /Q "DareDebuggerWV\obj"
DEL /Q /F /S "DareDebuggerWV\bin\Release\*.pdb"
DEL /Q /F /S "DareDebuggerWV\bin\Release\*.config"
DEL /Q /F /S "DareDebuggerWV\bin\Release\*.vshost.*"
RD /S /Q "DareParserWV\obj"
DEL /Q /F /S "DareParserWV\bin\Release\*.pdb"
DEL /Q /F /S "DareParserWV\bin\Release\*.config"
DEL /Q /F /S "DareParserWV\bin\Release\*.vshost.*"
RD /S /Q "GRP_Hook\AICLASS_PCClient_R\Release"
DEL /Q /F /S "GRP_Hook\Release\*.exp"
DEL /Q /F /S "GRP_Hook\Release\*.lib"
DEL /Q /F /S "GRP_Hook\Release\*.pdb"
RD /S /Q "GRPBackendWV\obj"
DEL /Q /F /S "GRPBackendWV\bin\Release\*.pdb"
DEL /Q /F /S "GRPBackendWV\bin\Release\*.config"
DEL /Q /F /S "GRPBackendWV\bin\Release\*.vshost.*"
DEL /Q /F /S "GRPBackendWV\bin\Release\*.txt"
RD /S /Q "GRPExplorerWV\obj"
DEL /Q /F /S "GRPExplorerWV\bin\Release\*.pdb"
DEL /Q /F /S "GRPExplorerWV\bin\Release\*.config"
DEL /Q /F /S "GRPExplorerWV\bin\Release\*.vshost.*"
DEL /Q /F /S "GRPBackendWV.sdf"
pause