RD /S /Q "Be.Windows.Forms.HexBox\obj"
RD /S /Q "Be.Windows.Forms.HexBox\bin\Debug"
RD /S /Q "Be.Windows.Forms.HexBox\bin\Release"
RD /S /Q "Be.Windows.Forms.HexBox\bin\x86\Debug"
DEL /Q /F /S "Be.Windows.Forms.HexBox\bin\x86\Release\*.pdb"
RD /S /Q "DareDebuggerWV\obj"
RD /S /Q "DareDebuggerWV\bin\Debug"
RD /S /Q "DareDebuggerWV\bin\Release"
RD /S /Q "DareDebuggerWV\bin\x86\Debug"
DEL /Q /F /S "DareDebuggerWV\bin\x86\Release\*.pdb"
DEL /Q /F /S "DareDebuggerWV\bin\x86\Release\*.config"
DEL /Q /F /S "DareDebuggerWV\bin\x86\Release\*.vshost.*"
RD /S /Q "DareParserWV\obj"
RD /S /Q "DareParserWV\bin\Debug"
RD /S /Q "DareParserWV\bin\Release"
RD /S /Q "DareParserWV\bin\x86\Debug"
DEL /Q /F /S "DareParserWV\bin\x86\Release\*.pdb"
DEL /Q /F /S "DareParserWV\bin\x86\Release\*.config"
DEL /Q /F /S "DareParserWV\bin\x86\Release\*.vshost.*"
RD /S /Q "DTBReaderWV\obj"
RD /S /Q "DTBReaderWV\bin\Debug"
RD /S /Q "DTBReaderWV\bin\Release"
RD /S /Q "DTBReaderWV\bin\x86\Debug"
DEL /Q /F /S "DTBReaderWV\bin\x86\Release\*.pdb"
DEL /Q /F /S "DTBReaderWV\bin\x86\Release\*.config"
DEL /Q /F /S "DTBReaderWV\bin\x86\Release\*.vshost.*"
RD /S /Q "GRO_Hook\AICLASS_PCClient_R\Release"
RD /S /Q "GRO_Hook\AICLASS_PCClient_R\Debug"
DEL /Q /F /S "GRO_Hook\x86\Release\*.exp"
DEL /Q /F /S "GRO_Hook\x86\Release\*.lib"
DEL /Q /F /S "GRO_Hook\x86\Release\*.pdb"
RD /S /Q "GROBackendWV\obj"
RD /S /Q "GROBackendWV\bin\Debug"
RD /S /Q "GROBackendWV\bin\Release"
RD /S /Q "GROBackendWV\bin\x86\Debug"
DEL /Q /F /S "GROBackendWV\bin\x86\Release\*.pdb"
DEL /Q /F /S "GROBackendWV\bin\x86\Release\*.config"
DEL /Q /F /S "GROBackendWV\bin\x86\Release\*.vshost.*"
DEL /Q /F /S "GROBackendWV\bin\x86\Release\*.txt"
DEL /Q /F /S "GROBackendWV\bin\x86\Release\*.bin"
RD /S /Q "GROExplorerWV\obj"
RD /S /Q "GROExplorerWV\bin\Debug"
RD /S /Q "GROExplorerWV\bin\Release"
RD /S /Q "GROExplorerWV\bin\x86\Debug"
DEL /Q /F /S "GROExplorerWV\bin\x86\Release\*.pdb"
DEL /Q /F /S "GROExplorerWV\bin\x86\Release\*.config"
DEL /Q /F /S "GROExplorerWV\bin\x86\Release\*.vshost.*"
RD /S /Q "GROMemoryToolWV\obj"
RD /S /Q "GROMemoryToolWV\bin\Debug"
RD /S /Q "GROMemoryToolWV\bin\Release"
RD /S /Q "GROMemoryToolWV\bin\x86\Debug"
DEL /Q /F /S "GROMemoryToolWV\bin\x86\Release\*.pdb"
DEL /Q /F /S "GROMemoryToolWV\bin\x86\Release\*.config"
DEL /Q /F /S "GROMemoryToolWV\bin\x86\Release\*.vshost.*"
RD /S /Q "QuazalSharkWV\obj"
RD /S /Q "QuazalSharkWV\bin\Debug"
RD /S /Q "QuazalSharkWV\bin\Release"
RD /S /Q "QuazalSharkWV\bin\x86\Debug"
DEL /Q /F /S "QuazalSharkWV\bin\x86\Release\*.pdb"
DEL /Q /F /S "QuazalSharkWV\bin\x86\Release\*.config"
DEL /Q /F /S "QuazalSharkWV\bin\x86\Release\*.vshost.*"
RD /S /Q "QuazalWV\obj"
RD /S /Q "QuazalWV\bin\Debug"
RD /S /Q "QuazalWV\bin\Release"
RD /S /Q "QuazalWV\bin\x86\Debug"
DEL /Q /F /S "QuazalWV\bin\x86\Release\*.pdb"
DEL /Q /F /S "QuazalWV\bin\x86\Release\*.config"
DEL /Q /F /S "QuazalWV\bin\x86\Release\*.vshost.*"
RD /S /Q "GRODedicatedServerWV\obj"
RD /S /Q "GRODedicatedServerWV\bin\Debug"
RD /S /Q "GRODedicatedServerWV\bin\Release"
RD /S /Q "GRODedicatedServerWV\bin\x86\Debug"
DEL /Q /F /S "GRODedicatedServerWV\bin\x86\Release\*.pdb"
DEL /Q /F /S "GRODedicatedServerWV\bin\x86\Release\*.config"
DEL /Q /F /S "GRODedicatedServerWV\bin\x86\Release\*.vshost.*"
DEL /Q /F /S "GRODedicatedServerWV\bin\x86\Release\*.txt"
DEL /Q /F /S "GRODedicatedServerWV\bin\x86\Release\*.bin"
DEL /Q /F /S "GROBackendWV.sdf"
RD /S /Q "ipch"
streams.exe -s -d
pause